// Study OS — shared demo data (ES module).
export const DATA = {
  user: {
    name: 'Alex Rivera', initials: 'AR', email: 'alex.rivera.ml@gmail.com',
    week: 9, phase: 1, streak: 23, onTrack: true,
    minutesToday: 64, goalMinutes: 120,
    totalHours: 118, watchHours: 41, stepsDone: 196, notesWritten: 52,
    repo: 'alexrivera/ai-first-principles-notes',
  },
  week: {
    n: 9, phase: 1, title: 'Eigenvectors & eigenvalues',
    why: "Eigenvectors are the axes a transformation doesn't knock over — the single most reused idea downstream. PCA, spectral clustering, PageRank, even why deep nets explode or vanish: all eigenvalue stories.",
    remember: 'Av = λv is a definition, not a trick. If you can say in one sentence what makes a vector "eigen", this week worked.',
  },
  steps: [
    { id: 's1', kind: 'watch', title: 'Eigenvectors and eigenvalues — Essence of linear algebra, ch. 14', src: '3Blue1Brown', min: 17, done: false, watched: 73, autoAt: 90, yt: 'PFDu9oVAE-g' },
    { id: 's2', kind: 'read', title: 'Linear Algebra Done Right — §5.A Invariant subspaces', src: 'Axler, pp. 132–140', min: 25, done: false, progress: 0 },
    { id: 's3', kind: 'build', title: 'Implement power iteration in NumPy; recover the top eigenvector of a 5×5', src: 'notebook 09-eigen.ipynb', min: 40, done: false },
    { id: 's4', kind: 'checkpoint', title: 'Checkpoint: diagonalize two matrices by hand, no peeking', src: 'week 9 checkpoint', min: 15, done: false },
    { id: 's5', kind: 'note', title: 'Write your learned / confused / built note for today', src: 'publishes to GitHub', min: 10, done: false },
  ],
  doneToday: [
    { id: 'd1', kind: 'watch', title: 'Change of basis — ch. 13 (rewatch)', min: 13 },
    { id: 'd2', kind: 'read', title: 'MML book — §4.4 Eigendecomposition intro', min: 18 },
  ],
  video: {
    yt: 'PFDu9oVAE-g', title: 'Eigenvectors and eigenvalues | Chapter 14, Essence of linear algebra',
    channel: '3Blue1Brown', dur: '17:16', watchedPct: 73,
    segments: [[0, 0.38], [0.42, 0.77]],
    confusing: [{ t: '6:42', label: 'why det(A−λI)=0 finds them' }],
  },
  books: [
    { id: 'b1', title: 'Mathematics for Machine Learning', authors: 'Deisenroth, Faisal, Ong', phase: 1, pages: 412, pct: 34, inApp: true, spine: '#42406a' },
    { id: 'b2', title: 'Linear Algebra Done Right', authors: 'Sheldon Axler', phase: 1, pages: 340, pct: 22, inApp: true, spine: '#2b4a3f' },
    { id: 'b3', title: 'Probabilistic Machine Learning', authors: 'Kevin P. Murphy', phase: 2, pages: 864, pct: 4, inApp: true, spine: '#4a3357' },
    { id: 'b4', title: 'Understanding Deep Learning', authors: 'Simon J.D. Prince', phase: 4, pages: 541, pct: 0, inApp: true, spine: '#274052' },
    { id: 'b5', title: 'Deep Learning', authors: 'Goodfellow, Bengio, Courville', phase: 4, pages: 800, pct: 0, inApp: false, spine: '#4f3b2b' },
    { id: 'b6', title: 'Dive into Deep Learning', authors: 'Zhang, Lipton, Li, Smola', phase: 4, pages: 1032, pct: 0, inApp: false, spine: '#31404f' },
    { id: 'b7', title: 'Speech and Language Processing', authors: 'Jurafsky & Martin', phase: 5, pages: 636, pct: 0, inApp: true, spine: '#503243' },
  ],
  papers: [
    { id: 'p1', title: 'Attention Is All You Need', authors: 'Vaswani et al., 2017', arxiv: '1706.03762', pages: 15, est: 90, week: 49 },
    { id: 'p2', title: 'ImageNet Classification with Deep CNNs', authors: 'Krizhevsky et al., 2012', arxiv: 'NeurIPS 2012', pages: 9, est: 60, week: 43 },
    { id: 'p3', title: 'Deep Residual Learning for Image Recognition', authors: 'He et al., 2015', arxiv: '1512.03385', pages: 12, est: 75, week: 43 },
    { id: 'p4', title: 'Batch Normalization', authors: 'Ioffe & Szegedy, 2015', arxiv: '1502.03167', pages: 11, est: 70, week: 41 },
    { id: 'p5', title: 'Dropout: A Simple Way to Prevent Overfitting', authors: 'Srivastava et al., 2014', arxiv: 'JMLR 15', pages: 30, est: 110, week: 41 },
    { id: 'p6', title: 'Adam: A Method for Stochastic Optimization', authors: 'Kingma & Ba, 2014', arxiv: '1412.6980', pages: 15, est: 80, week: 40 },
    { id: 'p7', title: 'Efficient Estimation of Word Representations', authors: 'Mikolov et al., 2013', arxiv: '1301.3781', pages: 12, est: 70, week: 45 },
    { id: 'p8', title: 'Generative Adversarial Networks', authors: 'Goodfellow et al., 2014', arxiv: '1406.2661', pages: 9, est: 65, week: 60 },
    { id: 'p9', title: 'Auto-Encoding Variational Bayes', authors: 'Kingma & Welling, 2013', arxiv: '1312.6114', pages: 14, est: 95, week: 60 },
    { id: 'p10', title: 'BERT: Pre-training of Deep Bidirectional Transformers', authors: 'Devlin et al., 2018', arxiv: '1810.04805', pages: 16, est: 85, week: 58 },
    { id: 'p11', title: 'Language Models are Few-Shot Learners', authors: 'Brown et al., 2020', arxiv: '2005.14165', pages: 75, est: 180, week: 54 },
    { id: 'p12', title: 'Scaling Laws for Neural Language Models', authors: 'Kaplan et al., 2020', arxiv: '2001.08361', pages: 30, est: 120, week: 55 },
  ],
  phases: [
    { n: 0, name: 'Foundations', range: '1–6', pct: 100, hrs: 58, weeks: [
      { w: 1, t: 'Python fluency & tooling', h: 9 }, { w: 2, t: 'NumPy & vectorized thinking', h: 10 },
      { w: 3, t: 'Functions, complexity & big-O', h: 9 }, { w: 4, t: 'Probability warm-up: counting & simulation', h: 10 },
      { w: 5, t: 'Calculus refresher: derivatives by hand', h: 10 }, { w: 6, t: 'Foundations checkpoint', h: 10, recap: true },
    ]},
    { n: 1, name: 'Linear algebra', range: '7–14', pct: 31, hrs: 82, weeks: [
      { w: 7, t: 'Vectors, span & linear combinations', h: 10 }, { w: 8, t: 'Matrices as transformations', h: 10 },
      { w: 9, t: 'Eigenvectors & eigenvalues', h: 11, now: true,
        guide: 'The payoff week. Everything before was setup; everything after leans on this.',
        steps: ['Watch 3B1B ch. 14 (17m)', 'Read Axler §5.A (25m)', 'Build power iteration in NumPy (40m)', 'Checkpoint: diagonalize by hand (15m)', 'Write & publish note (10m)'] },
      { w: 10, t: 'Determinants, rank & inverse', h: 10 }, { w: 11, t: 'Orthogonality & projections', h: 10 },
      { w: 12, t: 'SVD from scratch', h: 11 }, { w: 13, t: 'PCA: the eigenfaces project', h: 11 },
      { w: 14, t: 'Linear algebra checkpoint', h: 9, recap: true },
    ]},
    { n: 2, name: 'Calculus & probability', range: '15–24', pct: 0, hrs: 104, weeks: [
      { w: 15, t: 'Multivariable calculus & gradients', h: 10 }, { w: 16, t: 'The chain rule, computationally', h: 10 },
      { w: 17, t: 'Gradient descent by hand', h: 11 }, { w: 18, t: 'Convexity & learning rates', h: 10 },
      { w: 19, t: 'Random variables & distributions', h: 10 }, { w: 20, t: 'Bayes, likelihood & estimation', h: 11 },
      { w: 21, t: 'Information theory: entropy & KL', h: 10 }, { w: 22, t: 'Sampling & Monte Carlo', h: 10 },
      { w: 23, t: 'Statistics for experiments', h: 11 }, { w: 24, t: 'Math core checkpoint', h: 11, recap: true },
    ]},
    { n: 3, name: 'Classical ML', range: '25–36', pct: 0, hrs: 126, weeks: [
      { w: 25, t: 'Linear regression from scratch', h: 10 }, { w: 26, t: 'Logistic regression & boundaries', h: 10 },
      { w: 27, t: 'Regularization: ridge & lasso', h: 10 }, { w: 28, t: 'Feature engineering & pipelines', h: 11 },
      { w: 29, t: 'Trees & random forests', h: 10 }, { w: 30, t: 'Gradient boosting', h: 11 },
      { w: 31, t: 'SVMs & kernels', h: 11 }, { w: 32, t: 'Clustering: k-means & GMM', h: 10 },
      { w: 33, t: 'Dimensionality reduction in practice', h: 10 }, { w: 34, t: 'Evaluation & cross-validation', h: 11 },
      { w: 35, t: 'Kaggle project week', h: 12 }, { w: 36, t: 'Classical ML checkpoint', h: 10, recap: true },
    ]},
    { n: 4, name: 'Deep learning', range: '37–52', pct: 0, hrs: 178, weeks: [
      { w: 37, t: 'Perceptrons & the neuron', h: 10 }, { w: 38, t: 'Backpropagation by hand', h: 12 },
      { w: 39, t: 'micrograd: build autograd', h: 12 }, { w: 40, t: 'Training dynamics & Adam', h: 11, papers: ['Adam'] },
      { w: 41, t: 'Batch norm & dropout', h: 11, papers: ['Batch Normalization', 'Dropout'] },
      { w: 42, t: 'CNNs: convolutions from scratch', h: 12 }, { w: 43, t: 'AlexNet & ResNet deep read', h: 11, papers: ['AlexNet', 'ResNet'] },
      { w: 44, t: 'Vision checkpoint', h: 9, recap: true }, { w: 45, t: 'Embeddings & word2vec', h: 11, papers: ['word2vec'] },
      { w: 46, t: 'RNNs & LSTMs', h: 11 }, { w: 47, t: 'makemore: character-level LM', h: 12 },
      { w: 48, t: 'Attention from first principles', h: 12 }, { w: 49, t: "'Attention Is All You Need' deep read", h: 11, papers: ['Attention Is All You Need'] },
      { w: 50, t: 'Build a transformer: nanoGPT pt. 1', h: 12 }, { w: 51, t: 'nanoGPT pt. 2: training runs', h: 12 },
      { w: 52, t: 'Deep learning checkpoint', h: 10, recap: true },
    ]},
    { n: 5, name: 'Modern AI', range: '53–68', pct: 0, hrs: 172, weeks: [
      { w: 53, t: 'Tokenization: build BPE', h: 11 }, { w: 54, t: 'GPT-3 & few-shot learning', h: 11, papers: ['GPT-3'] },
      { w: 55, t: 'Scaling laws deep read', h: 10, papers: ['Scaling Laws'] }, { w: 56, t: 'Fine-tuning & LoRA', h: 11 },
      { w: 57, t: 'RLHF & instruction tuning', h: 11 }, { w: 58, t: 'BERT & encoder models', h: 10, papers: ['BERT'] },
      { w: 59, t: 'Vision transformers', h: 10 }, { w: 60, t: 'GANs & VAEs', h: 11, papers: ['GANs', 'VAE'] },
      { w: 61, t: 'Diffusion models', h: 12 }, { w: 62, t: 'Multimodal models', h: 10 },
      { w: 63, t: 'Retrieval & RAG systems', h: 11 }, { w: 64, t: 'Agents & tool use', h: 11 },
      { w: 65, t: 'Interpretability: features & circuits', h: 11 }, { w: 66, t: 'Alignment: problems & approaches', h: 10 },
      { w: 67, t: 'Evals & benchmarks', h: 10 }, { w: 68, t: 'Modern AI checkpoint', h: 10, recap: true },
    ]},
    { n: 6, name: 'Capstone', range: '69–77', pct: 0, hrs: 96, weeks: [
      { w: 69, t: 'Capstone: proposal & scoping', h: 10 }, { w: 70, t: 'Capstone: data & baseline', h: 11 },
      { w: 71, t: 'Capstone: core build', h: 11 }, { w: 72, t: 'Capstone: core build II', h: 11 },
      { w: 73, t: 'Capstone: evaluation', h: 11 }, { w: 74, t: 'Capstone: ablations', h: 10 },
      { w: 75, t: 'Capstone: write-up', h: 11 }, { w: 76, t: 'Publish & present', h: 10 },
      { w: 77, t: 'Retrospective & what comes next', h: 8, recap: true },
    ]},
  ],
  members: [
    { id: 'm1', name: 'Priya Sharma', ini: 'PS', pct: 14.2, stepsWeek: 21, streak: 31, week: 11, today: true },
    { id: 'm0', name: 'Alex Rivera', ini: 'AR', pct: 11.4, stepsWeek: 19, streak: 23, week: 9, today: true, you: true },
    { id: 'm2', name: 'Marcus Chen', ini: 'MC', pct: 11.1, stepsWeek: 16, streak: 12, week: 9, today: true },
    { id: 'm3', name: 'Tom Okafor', ini: 'TO', pct: 12.6, stepsWeek: 14, streak: 9, week: 10, today: false },
    { id: 'm4', name: 'Sofia Reyes', ini: 'SR', pct: 10.0, stepsWeek: 12, streak: 17, week: 8, today: true },
    { id: 'm5', name: 'Lena Vogel', ini: 'LV', pct: 8.8, stepsWeek: 9, streak: 4, week: 7, today: false },
    { id: 'm6', name: 'Dai Nguyen', ini: 'DN', pct: 11.2, stepsWeek: 8, streak: 6, week: 9, today: true },
  ],
  groupHoursWeek: 41.5,
  badges: [
    { id: 'g1', name: 'First light', desc: 'Studied before 6am', earned: true, icon: 'sun' },
    { id: 'g2', name: 'Week one done', desc: 'Completed week 1', earned: true, icon: 'flag' },
    { id: 'g3', name: '7-day streak', desc: 'Seven days straight', earned: true, icon: 'flame' },
    { id: 'g4', name: 'Bookworm', desc: 'First 100 pages read in app', earned: true, icon: 'book' },
    { id: 'g5', name: 'Builder', desc: 'First build step shipped', earned: true, icon: 'code' },
    { id: 'g6', name: 'Publisher', desc: 'First note pushed to GitHub', earned: true, icon: 'branch' },
    { id: 'g7', name: '30-day streak', desc: 'Thirty days straight', earned: false, icon: 'flame' },
    { id: 'g8', name: 'Paper cut', desc: 'First landmark paper finished', earned: false, icon: 'file' },
    { id: 'g9', name: 'Phase one', desc: 'Finish the math core', earned: false, icon: 'sigma' },
    { id: 'g10', name: 'Centurion', desc: '100 hours logged', earned: true, icon: 'clock' },
    { id: 'g11', name: 'Halfway', desc: 'Reach week 39 of 77', earned: false, icon: 'divide' },
    { id: 'g12', name: 'Observer observed', desc: '10 AI-distilled records reviewed', earned: false, icon: 'eye' },
  ],
  notes: [
    { id: 'n9', week: 9, title: 'Wk 9 · Eigenvectors & eigenvalues', date: 'Today, 5:58am', words: 312, published: false, current: true },
    { id: 'n8', week: 8, title: 'Wk 8 · Matrices as transformations', date: 'Jul 19', words: 748, published: true },
    { id: 'n7', week: 7, title: 'Wk 7 · Vectors & span', date: 'Jul 12', words: 691, published: true },
    { id: 'n6', week: 6, title: 'Wk 6 · Foundations checkpoint', date: 'Jul 5', words: 402, published: true },
    { id: 'n5', week: 5, title: 'Wk 5 · Derivatives by hand', date: 'Jun 28', words: 833, published: true },
    { id: 'n4', week: 4, title: 'Wk 4 · Probability warm-up', date: 'Jun 21', words: 577, published: true },
  ],
  admin: {
    pending: [
      { id: 'a1', name: 'Yuki Tanaka', email: 'yuki.t@proton.me', verified: true, ago: '2h ago', code: 'STUDY-7F2K' },
      { id: 'a2', name: 'Omar Haddad', email: 'omar.haddad@gmail.com', verified: false, ago: '1d ago', code: 'STUDY-7F2K' },
    ],
    members: [
      { id: 'm0', name: 'Alex Rivera', email: 'alex.rivera.ml@gmail.com', status: 'owner', active: 'now', watchH: 41.2 },
      { id: 'm1', name: 'Priya Sharma', email: 'priya.sh@outlook.com', status: 'active', active: '12m ago', watchH: 48.9 },
      { id: 'm2', name: 'Marcus Chen', email: 'mchen.dev@gmail.com', status: 'active', active: '1h ago', watchH: 37.4 },
      { id: 'm3', name: 'Tom Okafor', email: 'tokafor@hey.com', status: 'active', active: '2d ago', watchH: 40.1 },
      { id: 'm4', name: 'Sofia Reyes', email: 'sofia.r@gmail.com', status: 'active', active: '4h ago', watchH: 29.8 },
      { id: 'm5', name: 'Lena Vogel', email: 'lena.vogel@web.de', status: 'idle 14d', active: '14d ago', watchH: 18.2 },
      { id: 'm6', name: 'Dai Nguyen', email: 'dai.ng@gmail.com', status: 'active', active: '6h ago', watchH: 24.6 },
    ],
    invites: [
      { code: 'STUDY-7F2K', used: 5, cap: 10, note: 'reddit r/learnmachinelearning' },
      { code: 'STUDY-M3TA', used: 2, cap: 5, note: 'uni study group' },
    ],
    dau: [3, 4, 4, 5, 3, 6, 5, 6, 7, 5, 6, 7, 6, 7],
    watchWk: [4.2, 5.8, 5.1, 7.4, 6.9, 8.8, 9.6, 11.2],
    velocity: [38, 52, 47, 61, 58, 72, 69, 81],
  },
};
export function fmtMin(m) { return m >= 60 ? `${Math.floor(m / 60)}h ${m % 60 ? (m % 60) + 'm' : ''}`.trim() : `${m}m`; }
